name: Docker Image CI

on:
  workflow_dispatch:
  
env:
  IMAGE_TAG: cicd-test-${{ github.run_number }}-${{ github.run_id }}-$(date +%F)
  
jobs:

  build:

    runs-on: [self-hosted, Linux]

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.REPO}}:$IMAGE_TAG
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Push Docker images
      run: docker push ${{ secrets.REPO }}:$IMAGE_TAG
    
    - name: Cleanup build folder
      run: |
        ls -la ./
        rm -rf ./* || true
        rm -rf ./.??* || true
        ls -la ./
